# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Final_Prj.cache/wt [current_project]
set_property parent.project_path C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Final_Prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Final_Prj.srcs/sources_1/new/SPI_If.vhd
  C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Final_Prj.srcs/sources_1/new/ADXL362Ctrl.vhd
  C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Final_Prj.srcs/sources_1/new/top_module.vhd
}
read_xdc C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Timothy/Documents/GitHub/Lightshow2.0/Nexys4_Master.xdc]

synth_design -top top_module -part xc7a100tcsg324-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
